
# Register WORD1
RxVect_WORD1               = 0x0000
MASK_RxVect_MPDU_LENGTH    = 0x00FFFFFF
SHIFT_RxVect_MPDU_LENGTH   = 0
NBITS_RxVect_MPDU_LENGTH   = 24
REGNUM_RxVect_MPDU_LENGTH  = 0x0000
SIGNED_RxVect_MPDU_LENGTH  = 0
MAX_RxVect_MPDU_LENGTH     = 16777215
MIN_RxVect_MPDU_LENGTH     = 0

# Register WORD3
RxVect_WORD3                  = 0x0000
MASK_RxVect_TIME_OF_ARRIVAL   = 0x00FFFFFF
SHIFT_RxVect_TIME_OF_ARRIVAL  =  0
NBITS_RxVect_TIME_OF_ARRIVAL  =  24
REGNUM_RxVect_TIME_OF_ARRIVAL =  0x0000
SIGNED_RxVect_TIME_OF_ARRIVAL =  0
MAX_RxVect_TIME_OF_ARRIVAL    = 16777215
MIN_RxVect_TIME_OF_ARRIVAL    = 0

# Register WORD4
### Same as WORD3 #####
#RxVect_WORD4                0x0000
#MASK_RxVect_TIME_OF_ARRIVAL 0x00FFFFFF
#SHIFT_RxVect_TIME_OF_ARRIVAL 0
#NBITS_RxVect_TIME_OF_ARRIVAL 24
#REGNUM_RxVect_TIME_OF_ARRIVAL 0x0000
#SIGNED_RxVect_TIME_OF_ARRIVAL 0
#MAX_RxVect_TIME_OF_ARRIVAL  16777215
#MIN_RxVect_TIME_OF_ARRIVAL  0

# Register WORD5
RxVect_WORD5               = 0x0000
MASK_RxVect_DIGI_GAIN      = 0x000000FF
SHIFT_RxVect_DIGI_GAIN     = 0
NBITS_RxVect_DIGI_GAIN     = 8
REGNUM_RxVect_DIGI_GAIN    = 0x0000
SIGNED_RxVect_DIGI_GAIN    = 0
MAX_RxVect_DIGI_GAIN       = 255
MIN_RxVect_DIGI_GAIN       = 0

MASK_RxVect_MAPPED_GAIN     = 0x0000FF00
SHIFT_RxVect_MAPPED_GAIN    = 8
NBITS_RxVect_MAPPED_GAIN    = 8
REGNUM_RxVect_MAPPED_GAIN   = 0x0000
SIGNED_RxVect_MAPPED_GAIN   = 0
MAX_RxVect_MAPPED_GAIN      = 255
MIN_RxVect_MAPPED_GAIN      = 0

MASK_RxVect_EST_GAIN        = 0x00FF0000
SHIFT_RxVect_EST_GAIN       = 16
NBITS_RxVect_EST_GAIN       = 8
REGNUM_RxVect_EST_GAIN      = 0x0000
SIGNED_RxVect_EST_GAIN      = 0
MAX_RxVect_EST_GAIN         = 255
MIN_RxVect_EST_GAIN         = 0

MASK_RxVect_RSSI           = 0xFF000000
SHIFT_RxVect_RSSI          = 24
NBITS_RxVect_RSSI          = 8
REGNUM_RxVect_RSSI         = 0x0000
SIGNED_RxVect_RSSI         = 0
MAX_RxVect_RSSI            = 255
MIN_RxVect_RSSI            = 0

# Register WORD6           =
RxVect_WORD6               = 0x0000
MASK_RxVect_CFO            = 0x0000FFFF
SHIFT_RxVect_CFO           = 0
NBITS_RxVect_CFO           = 16
REGNUM_RxVect_CFO          = 0x0000
SIGNED_RxVect_CFO          = 0
MAX_RxVect_CFO             = 65535
MIN_RxVect_CFO             = 0

# Register WORD7           =
RxVect_WORD7               = 0x0000
MASK_RxVect_SFO            = 0x00FFFFFF
SHIFT_RxVect_SFO           = 0
NBITS_RxVect_SFO           = 24
REGNUM_RxVect_SFO          = 0x0000
SIGNED_RxVect_SFO          = 0
MAX_RxVect_SFO             = 16777215
MIN_RxVect_SFO             = 0

# Register WORD8           =
RxVect_WORD8               = 0x0000
MASK_RxVect_FSB            = 0x000000FF
SHIFT_RxVect_FSB           = 0
NBITS_RxVect_FSB           = 8
REGNUM_RxVect_FSB          = 0x0000
SIGNED_RxVect_FSB          = 0
MAX_RxVect_FSB             = 255
MIN_RxVect_FSB             = 0

MASK_RxVect_S2L_INDEX      = 0x000FFF00
SHIFT_RxVect_S2L_INDEX     = 8
NBITS_RxVect_S2L_INDEX     = 12
REGNUM_RxVect_S2L_INDEX    = 0x0000
SIGNED_RxVect_S2L_INDEX    = 0
MAX_RxVect_S2L_INDEX       = 4095
MIN_RxVect_S2L_INDEX       = 0

# Register WORD9           =
RxVect_WORD9               = 0x0000
MASK_RxVect_DC_EST         = 0x00FFFFFF
SHIFT_RxVect_DC_EST        = 0
NBITS_RxVect_DC_EST        = 24
REGNUM_RxVect_DC_EST       = 0x0000
SIGNED_RxVect_DC_EST       = 0
MAX_RxVect_DC_EST          = 16777215
MIN_RxVect_DC_EST          = 0

# Register WORD10          =
RxVect_WORD10              = 0x0000
MASK_RxVect_EVM_EST        = 0x000000FF
SHIFT_RxVect_EVM_EST       = 0
NBITS_RxVect_EVM_EST       = 8
REGNUM_RxVect_EVM_EST      = 0x0000
SIGNED_RxVect_EVM_EST      = 0
MAX_RxVect_EVM_EST         = 255
MIN_RxVect_EVM_EST         = 0

MASK_RxVect_SNR_EST        = 0x0000FF00
SHIFT_RxVect_SNR_EST       = 8
NBITS_RxVect_SNR_EST       = 8
REGNUM_RxVect_SNR_EST      = 0x0000
SIGNED_RxVect_SNR_EST      = 0
MAX_RxVect_SNR_EST         = 255
MIN_RxVect_SNR_EST         = 0

# Register WORD11          =
RxVect_WORD11              = 0x0000
MASK_RxVect_HEADER_BYTES   = 0xFFFFFFFF
SHIFT_RxVect_HEADER_BYTES  = 0
NBITS_RxVect_HEADER_BYTES  = 32
REGNUM_RxVect_HEADER_BYTES = 0x0000
SIGNED_RxVect_HEADER_BYTES = 0
MAX_RxVect_HEADER_BYTES    = 4294967295
MIN_RxVect_HEADER_BYTES    = 0

# Register WORD12          =
RxVect_WORD12              = 0x0000
MASK_RxVect_HEADER_BYTES   = 0xFFFFFFFF
SHIFT_RxVect_HEADER_BYTES  = 0
NBITS_RxVect_HEADER_BYTES  = 32
REGNUM_RxVect_HEADER_BYTES = 0x0000
SIGNED_RxVect_HEADER_BYTES = 0
MAX_RxVect_HEADER_BYTES    = 4294967295
MIN_RxVect_HEADER_BYTES    = 0

# Register WORD13          =
RxVect_WORD13              = 0x0000
MASK_RxVect_HEADER_BYTES   = 0xFFFFFFFF
SHIFT_RxVect_HEADER_BYTES  = 0
NBITS_RxVect_HEADER_BYTES  = 32
REGNUM_RxVect_HEADER_BYTES = 0x0000
SIGNED_RxVect_HEADER_BYTES = 0
MAX_RxVect_HEADER_BYTES    = 4294967295
MIN_RxVect_HEADER_BYTES    = 0

# Register WORD14          =
RxVect_WORD14              = 0x0000
MASK_RxVect_HEADER_BYTES14   = 0x000000FF
SHIFT_RxVect_HEADER_BYTES14  = 0
NBITS_RxVect_HEADER_BYTES14  = 8
REGNUM_RxVect_HEADER_BYTES14 = 0x0000
SIGNED_RxVect_HEADER_BYTES14 = 0
MAX_RxVect_HEADER_BYTES14    = 255
MIN_RxVect_HEADER_BYTES14    = 0

# Register WORD2           =
RxVect_WORD2               = 0x0004
MASK_RxVect_FRAME_FORMAT   = 0x00000007
SHIFT_RxVect_FRAME_FORMAT  = 0
NBITS_RxVect_FRAME_FORMAT  = 3
REGNUM_RxVect_FRAME_FORMAT = 0x0004
SIGNED_RxVect_FRAME_FORMAT = 0
MAX_RxVect_FRAME_FORMAT    = 7
MIN_RxVect_FRAME_FORMAT    = 0

MASK_RxVect_NON_HT_MOD     = 0x00000100
SHIFT_RxVect_NON_HT_MOD    = 8
NBITS_RxVect_NON_HT_MOD    = 1
REGNUM_RxVect_NON_HT_MOD   = 0x0004
SIGNED_RxVect_NON_HT_MOD   = 0
MAX_RxVect_NON_HT_MOD      = 1
MIN_RxVect_NON_HT_MOD      = 0

MASK_RxVect_SBW            = 0x00030000
SHIFT_RxVect_SBW           = 16
NBITS_RxVect_SBW           = 2
REGNUM_RxVect_SBW          = 0x0004
SIGNED_RxVect_SBW          = 0
MAX_RxVect_SBW             = 3
MIN_RxVect_SBW             = 0

MASK_RxVect_MCS_OR_RATE    = 0xFF000000
SHIFT_RxVect_MCS_OR_RATE   = 24
NBITS_RxVect_MCS_OR_RATE   = 8
REGNUM_RxVect_MCS_OR_RATE  = 0x0004
SIGNED_RxVect_MCS_OR_RATE  = 0
MAX_RxVect_MCS_OR_RATE     = 255
MIN_RxVect_MCS_OR_RATE     = 0

# Register WORD15          =
MASK_RxVect_SERVICE_BYTES  = 0x0000FFFF
SHIFT_RxVect_SERVICE_BYTES = 0

######################### Header Definitions ######################################3

#Register N_TXP_RXVECT_L_SIG_CONTROL (PMR_WLAN_TXP)
RXVECT_L_SIG_CONTROL         = 0x0164
RXVECT_L_SIG_CONTROL       = 0xA500A164

WLAN_HEADER_L_SIG_RATE_MASK         = 0x0000000F
WLAN_HEADER_L_SIG_RATE_WIDTH        = 4
WLAN_HEADER_L_SIG_RATE_SHIFT        = 0
WLAN_HEADER_L_SIG_RATE_SIGNED       = 0

WLAN_HEADER_L_SIG_LENGTH_MASK       = 0x0001FFE0
WLAN_HEADER_L_SIG_LENGTH_WIDTH      = 12
WLAN_HEADER_L_SIG_LENGTH_SHIFT      = 5
WLAN_HEADER_L_SIG_LENGTH_SIGNED     = 0

# Register WLAN_TXP_HEADER_GENERATOR_HT_SIG1_CONTROL = (PMR_WLAN_TXP) */
WLAN_HEADER_HT_SIG1_CONTROL         =  0x0168
ABS_WLAN_HEADER_HT_SIG1_CONTROL     =  0xA500A168

WLAN_HEADER_HT_SIG1_MCS_MASK        =  0x0000007F
WLAN_HEADER_HT_SIG1_MCS_WIDTH       =  7
WLAN_HEADER_HT_SIG1_MCS_SHIFT       =  0
WLAN_HEADER_HT_SIG1_MCS_SIGNED      =  0

WLAN_HEADER_HT_SIG1_HT_LENGTH_MASK  =  0x00FFFF00
WLAN_HEADER_HT_SIG1_HT_LENGTH_WIDTH =  16
WLAN_HEADER_HT_SIG1_HT_LENGTH_SHIFT =  8
WLAN_HEADER_HT_SIG1_HT_LENGTH_SIGNED=  0

# Register WLAN_TXP_HEADER_GENERATOR_HT_SIG2_CONTROL = (PMR_WLAN_TXP) */
WLAN_HEADER_HT_SIG2_CONTROL         =     0x016C
ABS_WLAN_HEADER_HT_SIG2_CONTROL     =     0xA500A16C

WLAN_HEADER_HT_SIG2_SMOOTHING_MASK  =     0x00000001
WLAN_HEADER_HT_SIG2_SMOOTHING_WIDTH =     1
WLAN_HEADER_HT_SIG2_SMOOTHING_SHIFT =     0
WLAN_HEADER_HT_SIG2_SMOOTHING_SIGNED =     0

WLAN_HEADER_HT_SIG2_NOT_SOUNDING_MASK   = 0x00000002
WLAN_HEADER_HT_SIG2_NOT_SOUNDING_WIDTH  = 1
WLAN_HEADER_HT_SIG2_NOT_SOUNDING_SHIFT  = 1
WLAN_HEADER_HT_SIG2_NOT_SOUNDING_SIGNED = 0

WLAN_HEADER_HT_SIG2_AGGREGATION_MASK    = 0x00000008
WLAN_HEADER_HT_SIG2_AGGREGATION_WIDTH   = 1
WLAN_HEADER_HT_SIG2_AGGREGATION_SHIFT   = 3
WLAN_HEADER_HT_SIG2_AGGREGATION_SIGNED  = 0

WLAN_HEADER_HT_SIG2_STBC_MASK           = 0x00000030
WLAN_HEADER_HT_SIG2_STBC_WIDTH          = 2
WLAN_HEADER_HT_SIG2_STBC_SHIFT          = 4
WLAN_HEADER_HT_SIG2_STBC_SIGNED         = 0

WLAN_HEADER_HT_SIG2_FEC_CODING_MASK     = 0x00000040
WLAN_HEADER_HT_SIG2_FEC_CODING_WIDTH    = 1
WLAN_HEADER_HT_SIG2_FEC_CODING_SHIFT    = 6
WLAN_HEADER_HT_SIG2_FEC_CODING_SIGNED   = 0

WLAN_HEADER_HT_SIG2_SHORT_GI_MASK       = 0x00000080
WLAN_HEADER_HT_SIG2_SHORT_GI_WIDTH      = 1
WLAN_HEADER_HT_SIG2_SHORT_GI_SHIFT      = 7
WLAN_HEADER_HT_SIG2_SHORT_GI_SIGNED     = 0

WLAN_HEADER_HT_SIG2_NUM_EXT_SS_MASK     = 0x00000300
WLAN_HEADER_HT_SIG2_NUM_EXT_SS_WIDTH    = 2
WLAN_HEADER_HT_SIG2_NUM_EXT_SS_SHIFT    = 8
WLAN_HEADER_HT_SIG2_NUM_EXT_SS_SIGNED   = 0

# Register WLAN_TXP_HEADER_GENERATOR_VHT_SIG_A1_CONTROL (PMR_WLAN_TXP) */
WLAN_HEADER_VHT_SIG_A1_CONTROL                    = 0x0170
ABS_WLAN_HEADER_VHT_SIG_A1_CONTROL                = 0xA500A170

WLAN_HEADER_VHT_SIG_A1_GROUP_ID_MASK              = 0x000003F0
WLAN_HEADER_VHT_SIG_A1_GROUP_ID_WIDTH             = 6
WLAN_HEADER_VHT_SIG_A1_GROUP_ID_SHIFT             = 4
WLAN_HEADER_VHT_SIG_A1_GROUP_ID_SIGNED            = 0

WLAN_HEADER_VHT_SIG_A1_NSTS_PARTIAL_AID_MASK      = 0x003FFC00
WLAN_HEADER_VHT_SIG_A1_NSTS_PARTIAL_AID_WIDTH     = 12
WLAN_HEADER_VHT_SIG_A1_NSTS_PARTIAL_AID_SHIFT     = 10
WLAN_HEADER_VHT_SIG_A1_NSTS_PARTIAL_AID_SIGNED    = 0

WLAN_HEADER_VHT_SIG_A1_TXOP_PS_NOT_ALLOWED_MASK   = 0x00400000
WLAN_HEADER_VHT_SIG_A1_TXOP_PS_NOT_ALLOWED_WIDTH  = 1
WLAN_HEADER_VHT_SIG_A1_TXOP_PS_NOT_ALLOWED_SHIFT  = 22
WLAN_HEADER_VHT_SIG_A1_TXOP_PS_NOT_ALLOWED_SIGNED = 0

# Register WLAN_TXP_HEADER_GENERATOR_VHT_SIG_A2_CONTROL (PMR_WLAN_TXP) */
WLAN_HEADER_VHT_SIG_A2_CONTROL                       = 0x0174
ABS_WLAN_HEADER_VHT_SIG_A2_CONTROL                   = 0xA500A174

WLAN_HEADER_VHT_SIG_A2_SHORT_GI_NSYM_DISAMBIG_MASK   = 0x00000002
WLAN_HEADER_VHT_SIG_A2_SHORT_GI_NSYM_DISAMBIG_WIDTH  = 1
WLAN_HEADER_VHT_SIG_A2_SHORT_GI_NSYM_DISAMBIG_SHIFT  = 1
WLAN_HEADER_VHT_SIG_A2_SHORT_GI_NSYM_DISAMBIG_SIGNED = 0

WLAN_HEADER_VHT_SIG_A2_SU_MU0_CODING_MASK            = 0x00000004
WLAN_HEADER_VHT_SIG_A2_SU_MU0_CODING_WIDTH           = 1
WLAN_HEADER_VHT_SIG_A2_SU_MU0_CODING_SHIFT           = 2
WLAN_HEADER_VHT_SIG_A2_SU_MU0_CODING_SIGNED          = 0

WLAN_HEADER_VHT_SIG_A2_LDPC_EXTRA_SYM_MASK           = 0x00000008
WLAN_HEADER_VHT_SIG_A2_LDPC_EXTRA_SYM_WIDTH          = 1
WLAN_HEADER_VHT_SIG_A2_LDPC_EXTRA_SYM_SHIFT          = 3
WLAN_HEADER_VHT_SIG_A2_LDPC_EXTRA_SYM_SIGNED         = 0

WLAN_HEADER_VHT_SIG_A2_BEAMFORMED_MASK               = 0x00000100
WLAN_HEADER_VHT_SIG_A2_BEAMFORMED_WIDTH              = 1
WLAN_HEADER_VHT_SIG_A2_BEAMFORMED_SHIFT              = 8
WLAN_HEADER_VHT_SIG_A2_BEAMFORMED_SIGNED             = 0

# Register WLAN_TXP_HEADER_GENERATOR_VHT_SIG_B_CONTROL (PMR_WLAN_TXP) */
WLAN_HEADER_VHT_SIG_B_CONTROL       = 0x0178
ABS_WLAN_HEADER_VHT_SIG_B_CONTROL   = 0xA500A178
 
WLAN_HEADER_VHT_SIG_B_LENGTH_MASK   = 0x001FFFFF
WLAN_HEADER_VHT_SIG_B_LENGTH_WIDTH  = 21
WLAN_HEADER_VHT_SIG_B_LENGTH_SHIFT  = 0
WLAN_HEADER_VHT_SIG_B_LENGTH_SIGNED = 0
